name: entreprepare
description: "Entreprepare - Startup business idea recommendation app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.12
  flutter_markdown: ^0.7.0
  cached_network_image: ^3.2.3
  http: ^0.13.6
  video_player: ^2.6.0
  chewie: ^1.6.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.0.0
  uuid: ^4.0.0
  cloud_functions: 5.6.2
  shared_preferences: ^2.3.2
  webview_flutter: ^4.7.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0

  # Google Sign In
  google_sign_in: ^6.2.1

  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^0.2.7
  flutter_launcher_icons: ^0.12.0


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_icon.png
