// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsux4FdGfwC-nJbr1PtwNPpe9p-s14BrE',
    appId: '1:505608354835:android:60c820cc36618dd18713e6',
    messagingSenderId: '505608354835',
    projectId: 'entreprepare-e1d7d',
    storageBucket: 'entreprepare-e1d7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG3X5KcUr-20UXRnYTvq_tCIyz5LD5TWI',
    appId: '1:505608354835:ios:476852cbc5d4025c8713e6',
    messagingSenderId: '505608354835',
    projectId: 'entreprepare-e1d7d',
    storageBucket: 'entreprepare-e1d7d.firebasestorage.app',
    androidClientId: '505608354835-5d9m1lgnkdbacm7gcke64jn0cif2l5ej.apps.googleusercontent.com',
    iosClientId: '505608354835-ss63d1cculuk4vna63t89mrtvaoa9eih.apps.googleusercontent.com',
    iosBundleId: 'com.example.entreprepare',
  );

}